service:
  name: line-memo-pad
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: nodejs10.x

functions:
  main:
    handler: handler.main
    events:
      - http:
          method: post
          path: main
